# Generated by Django 3.2.3 on 2021-05-29 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datasets', '0010_auto_20210529_1637'),
        ('users', '0002_user_stars'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='contributions',
            field=models.ManyToManyField(to='datasets.Contribution'),
        ),
    ]
